config/routes.rb
Zad3::Application.routes.draw do

devise_for :users

get "home/index"
  
namespace "admin" do
  resources :firms do
   resources :workers
 end
end

root :to => "home#index"
end

app/models/firm.rb
class Firm < ActiveRecord::Base
  has_many :workers, :dependent => :destroy
  validates_presence_of :title
  
  before_create :fill_description
  
  protected
  def fill_description
    if description == "" then
      self.description  = "Firma " + title
    end
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :lockable, :timeoutable, :confirmable and :activatable
  devise :database_authenticatable, :registerable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation
end

app/models/worker.rb
class Worker < ActiveRecord::Base
  belongs_to :firm
  
  validates_presence_of :name
  validates_presence_of :age
  
end

app/controllers/admin/firms_controller.rb
class Admin::FirmsController < Admin::AdminController
  def index
    @firms = Firm.all
  end
  
  def new
    @firm = Firm.new
  end
  
  def create
    @firm = Firm.new(params[:firm])
    @firm.save
    if @firm.save
      redirect_to admin_firms_path
    else
      render :action => "new"
    end
  end
  def edit
    @firm = Firm.find(params[:id])
  end
  
  def show
    
  end
  
   def update
    @firm = Firm.find(params[:id])
    @firm.update_attributes(params[:firm])
    redirect_to admin_firms_path
  end
  
  def destroy
    @firm = Firm.find(params[:id])
    @firm.destroy
    redirect_to :action => 'index'
  end
  

  
end

app/controllers/admin/workers_controller.rb
class Admin::WorkersController < Admin::AdminController
  def index
    @firm = Firm.find(params[:firm_id])
    @workers = @firm.workers
  end
  
  def new
    @firm = Firm.find(params[:firm_id])
    @worker = @firm.workers.build
  end
  
  def create
    @firm = Firm.find(params[:firm_id])
    @worker = @firm.workers.build(params[:worker])
    if @worker.save
      redirect_to admin_firm_workers_path(@firm)
    else
      render :action => "new"
    end
    
  end
  

  
  def edit
    @firm = Firm.find(params[:firm_id])
    @worker = Worker.find(params[:id])
  end
  
   def update
    @firm = Firm.find(params[:firm_id])
    @worker = Worker.find(params[:id])
    @worker.update_attributes(params[:worker])
    redirect_to admin_firm_workers_path(@firm)
  end
  
  def destroy
      @firm = Firm.find(params[:firm_id]) 
      @worker = Worker.find(params[:id]) 
      @worker.destroy 
      redirect_to admin_firm_workers_path(@firm) 
  end
  
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_filter :authenticate_user!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @firms = Firm.all
  end
  
  
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/firm_helper.rb
module FirmHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/worker_helper.rb
module WorkerHelper
end

app/views/admin/firms/_error_msg.html.erb
<% if target.errors.any? %>  
  <div>  
     <% target.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %> 
  </div>  
<% end %>  

app/views/admin/firms/_form.html.erb
<% form_for([:admin, @firm]) do |f| %>
	
  <p>
  	<%= render 'error_msg', :target => @firm %>  
  </p>
  <p>
    <%= f.label :Nazwa %><br />
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :Opis %><br />
    <%= f.text_area :description %>
  </p>
  
  <p>
  	<%= f.submit 'Zapisz' %>
  </p>
<% end %>

app/views/admin/firms/edit.html.erb
<h2>Edycja</h2>

<%= render 'form' %>

<%= link_to 'Wróć', admin_firms_path %>

app/views/admin/firms/index.html.erb
<a href="/">Strona główna</a>
<br><br>
<h2>Lista firm</h2>
<% @firms.each do |firm| %>
	Nazwa: <%=h firm.title %> <br>
	Opis: <%=h firm.description %> <br>
	
	<%= link_to 'Lista pracowników', admin_firm_workers_path(firm) %>
	<%= link_to 'Edytuj', edit_admin_firm_path(firm) %>
	<%= link_to 'Usun', admin_firm_path(firm), :method => :delete %><br>
	<br>
<% end %>
<%= link_to 'Nowa firma', new_admin_firm_path %>

app/views/admin/firms/new.html.erb
<h2>Nowa firma</h2>

<%= render 'form' %>

<%= link_to 'Wróć', admin_firms_path %>

app/views/admin/workers/_error_msg.html.erb
<% if target.errors.any? %>  
  <div>  
     <% target.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %> 
  </div>  
<% end %>  

app/views/admin/workers/_form.html.erb
<% form_for([:admin, @firm, @worker]) do |f| %>
  <p>
  	<%= render 'error_msg', :target => @worker %>  
  </p>
  
  <p>
    Imię i nazwisko<br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :Wiek %><br />
    <%= f.text_field :age %>
  </p>
  <p>
  	 <%= f.label :gender, "Płeć:" %>
        <%=
          f.select :gender,
                       [["Kobieta", "Kobieta"], ["Mężczyzna", "Mężczyzna"]], 
                      :prompt => "Wybierz płeć"
        %>
  </p>	
  <p>
   	<%= f.submit 'Zapisz' %>
  </p>
  
<% end %>

app/views/admin/workers/edit.html.erb
<h2>Edytuj Pracownika</h2>

<%= render 'form' %>

<%= link_to 'Wróć', admin_firm_workers_path %>

app/views/admin/workers/index.html.erb
<a href="/">Strona główna</a>
<br><br>
<h2>Lista pracowników</h2>
<% @workers.each do |worker| %>
Imię i Nazwisko: <%=h worker.name%><br>
Wiek: <%=h worker.age%><br>
Płeć: <%=h worker.gender%><br>
<%= link_to 'Edytuj pracownika', edit_admin_firm_worker_path(@firm, worker) %>
<%= link_to 'Usun pracownika', admin_firm_worker_path(@firm, worker), :method => :delete %>
<br><br>
<%end%>
<%= link_to 'Dodaj pracownika', new_admin_firm_worker_path(@firm) %><br>
<%= link_to 'Wróć', admin_firms_path %>

app/views/admin/workers/new.html.erb
<h2>Dodaj Pracownika</h2>

<%= render 'form' %>

<%= link_to 'Wróć', admin_firm_workers_path(@firm) %>

app/views/home/index.html.erb
<%= link_to 'Panel Administracyjny' ,admin_firms_path%>
<br><br>
<h2>Lista firm</h2>
<br>
<% @firms.each do |firm| %>
	Nazwa: <%=h firm.title %> <br>
	Opis: <%=h firm.description %>
	<br><br>
<% end %>	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Zad3</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<%= notice %>
 <% if user_signed_in? %>
    Zalogowany jako: <%= current_user.email %>. 
    <%= link_to 'Wyloguj', destroy_user_session_path%>
 <% else %>
   <%= link_to 'Zaloguj', new_user_session_path%> lub <%= link_to 'Zarejestruj', new_user_registration_path %>
 <% end %>
 <br>
<%= yield %>

</body>
</html>